name: Release | Docker
on:
  workflow_dispatch:
    inputs:
      MFC_VERSION:
        required: true
        type: string
        description: Version of @ziemniakoss/mfc to use
      IMAGE_VERSION:
        required: true
        type: string
        description: Created image tag
jobs:
  deploy_to_docker:
    environment: docker
    runs-on: ubuntu-22.04
    name: Deploy to docker
    steps:
      - name: "Build image"
        run: docker build --build-arg mfc_version=${{ github.event.inputs.MFC_VERSION }} -t ziemniakoss/mfc:latest .
      - name: "Tag version"
        run: docker tag ziemniakoss/mfc:latest ziemniakoss/mfc:$${{ github.event.inputs.IMAGE_VERSION }}
      - name: "Authorize to docker hub"
        run: echo $${{ secrets.DOCKER_TOKEN }} | docker login --username ziemniakoss --password-stdin
      - name: "Push tags to docker"
        run: git push origin -a ziemniakoss/mfc
